/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const AccessPolicyTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    OPEN: 'Open',

    /**
     * TODO: Write general description for this element
     */
    ENUM_CUSTOM_ACCESS_POLICY: 'Custom access policy',

    /**
     * TODO: Write general description for this element
     */
    ENUM_MAC_ALLOW_LIST: 'MAC allow list',

    /**
     * TODO: Write general description for this element
     */
    ENUM_STICKY_MAC_ALLOW_LIST: 'Sticky MAC allow list',

};

module.exports = AccessPolicyTypeEnum;
