/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const AccessCategoryEnum = {

    /**
     * TODO: Write general description for this element
     */
    BACKGROUND_TRAFFIC: 'backgroundTraffic',

    /**
     * TODO: Write general description for this element
     */
    BEST_EFFORT_TRAFFIC: 'bestEffortTraffic',

    /**
     * TODO: Write general description for this element
     */
    VIDEO_TRAFFIC: 'videoTraffic',

    /**
     * TODO: Write general description for this element
     */
    VOICE_TRAFFIC: 'voiceTraffic',

};

module.exports = AccessCategoryEnum;
