/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of AccessPoint
 */
class AccessPoint extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.serial = this.constructor.getValue(obj.serial);
        this.alternateManagementIp = this.constructor.getValue(obj.alternateManagementIp);
        this.subnetMask = this.constructor.getValue(obj.subnetMask);
        this.gateway = this.constructor.getValue(obj.gateway);
        this.dns1 = this.constructor.getValue(obj.dns1);
        this.dns2 = this.constructor.getValue(obj.dns2);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'serial', realName: 'serial' },
            { name: 'alternateManagementIp', realName: 'alternateManagementIp' },
            { name: 'subnetMask', realName: 'subnetMask' },
            { name: 'gateway', realName: 'gateway' },
            { name: 'dns1', realName: 'dns1' },
            { name: 'dns2', realName: 'dns2' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = AccessPoint;
