/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Access6Enum = {

    /**
     * TODO: Write general description for this element
     */
    FULL: 'full',

    /**
     * TODO: Write general description for this element
     */
    READONLY: 'read-only',

    /**
     * TODO: Write general description for this element
     */
    GUESTAMBASSADOR: 'guest-ambassador',

    /**
     * TODO: Write general description for this element
     */
    MONITORONLY: 'monitor-only',

};

module.exports = Access6Enum;
