/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const AccessPolicyType1Enum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_8021_X: '802.1x',

    /**
     * TODO: Write general description for this element
     */
    ENUM_MAC_AUTHENTICATION_BYPASS: 'MAC authentication bypass',

    /**
     * TODO: Write general description for this element
     */
    ENUM_HYBRID_AUTHENTICATION: 'Hybrid authentication',

};

module.exports = AccessPolicyType1Enum;
