/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const AccessEnum = {

    /**
     * TODO: Write general description for this element
     */
    BLOCKED: 'blocked',

    /**
     * TODO: Write general description for this element
     */
    RESTRICTED: 'restricted',

    /**
     * TODO: Write general description for this element
     */
    UNRESTRICTED: 'unrestricted',

};

module.exports = AccessEnum;
