/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const AccountTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    GUEST: 'Guest',

    /**
     * TODO: Write general description for this element
     */
    ENUM_8021_X: '802.1X',

    /**
     * TODO: Write general description for this element
     */
    ENUM_CLIENT_VPN: 'Client VPN',

};

module.exports = AccountTypeEnum;
