/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const AreaTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    NORMAL: 'normal',

    /**
     * TODO: Write general description for this element
     */
    STUB: 'stub',

    /**
     * TODO: Write general description for this element
     */
    NSSA: 'nssa',

};

module.exports = AreaTypeEnum;
