/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const AuthModeEnum = {

    /**
     * TODO: Write general description for this element
     */
    OPEN: 'open',

    /**
     * TODO: Write general description for this element
     */
    PSK: 'psk',

    /**
     * TODO: Write general description for this element
     */
    OPENWITHRADIUS: 'open-with-radius',

    /**
     * TODO: Write general description for this element
     */
    ENUM_8021_XMERAKI: '8021x-meraki',

    /**
     * TODO: Write general description for this element
     */
    ENUM_8021_XRADIUS: '8021x-radius',

    /**
     * TODO: Write general description for this element
     */
    ENUM_8021_XGOOGLE: '8021x-google',

    /**
     * TODO: Write general description for this element
     */
    ENUM_8021_XLOCALRADIUS: '8021x-localradius',

    /**
     * TODO: Write general description for this element
     */
    IPSKWITHRADIUS: 'ipsk-with-radius',

    /**
     * TODO: Write general description for this element
     */
    IPSKWITHOUTRADIUS: 'ipsk-without-radius',

};

module.exports = AuthModeEnum;
