/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const AuthenticationMethodEnum = {

    /**
     * TODO: Write general description for this element
     */
    EMAIL: 'Email',

    /**
     * TODO: Write general description for this element
     */
    ENUM_CISCO_SECURE_X_SIGN_ON: 'Cisco SecureX Sign-On',

};

module.exports = AuthenticationMethodEnum;
