/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BandEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_24: '2.4',

    /**
     * TODO: Write general description for this element
     */
    ENUM_5: '5',

};

module.exports = BandEnum;
