/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BandSelectionTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    SSID: 'ssid',

    /**
     * TODO: Write general description for this element
     */
    AP: 'ap',

};

module.exports = BandSelectionTypeEnum;
