/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Billing
 */
class Billing extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.freeAccess = this.constructor.getValue(obj.freeAccess);
        this.prepaidAccessFastLoginEnabled =
          this.constructor.getValue(obj.prepaidAccessFastLoginEnabled);
        this.replyToEmailAddress = this.constructor.getValue(obj.replyToEmailAddress);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'freeAccess', realName: 'freeAccess', type: 'FreeAccess' },
            { name: 'prepaidAccessFastLoginEnabled', realName: 'prepaidAccessFastLoginEnabled' },
            { name: 'replyToEmailAddress', realName: 'replyToEmailAddress' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Billing;
