/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BuiltinPerformanceClassNameEnum = {

    /**
     * TODO: Write general description for this element
     */
    VO_IP: 'VoIP',

};

module.exports = BuiltinPerformanceClassNameEnum;
