/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const CategoryEnum = {

    /**
     * TODO: Write general description for this element
     */
    PERFORMANCE: 'performance',

    /**
     * TODO: Write general description for this element
     */
    STABILITY: 'stability',

    /**
     * TODO: Write general description for this element
     */
    ENUM_BROKE_OLD_FEATURES: 'broke old features',

    /**
     * TODO: Write general description for this element
     */
    ENUM_UNIFYING_NETWORKS_VERSIONS: 'unifying networks versions',

    /**
     * TODO: Write general description for this element
     */
    TESTING: 'testing',

    /**
     * TODO: Write general description for this element
     */
    OTHER: 'other',

};

module.exports = CategoryEnum;
