/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CertificateAuthentication
 */
class CertificateAuthentication extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.enabled = this.constructor.getValue(obj.enabled);
        this.useLdap = this.constructor.getValue(obj.useLdap);
        this.useOcsp = this.constructor.getValue(obj.useOcsp);
        this.ocspResponderUrl = this.constructor.getValue(obj.ocspResponderUrl);
        this.clientRootCaCertificate = this.constructor.getValue(obj.clientRootCaCertificate);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'enabled', realName: 'enabled' },
            { name: 'useLdap', realName: 'useLdap' },
            { name: 'useOcsp', realName: 'useOcsp' },
            { name: 'ocspResponderUrl', realName: 'ocspResponderUrl' },
            {
                name: 'clientRootCaCertificate',
                realName: 'clientRootCaCertificate',
                type: 'ClientRootCaCertificate',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CertificateAuthentication;
