/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ChannelWidthEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_0: 0,

    /**
     * TODO: Write general description for this element
     */
    ENUM_20: 20,

    /**
     * TODO: Write general description for this element
     */
    ENUM_40: 40,

    /**
     * TODO: Write general description for this element
     */
    ENUM_80: 80,

    /**
     * TODO: Write general description for this element
     */
    ENUM_160: 160,

};

module.exports = ChannelWidthEnum;
