/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Channel1Enum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_36: 36,

    /**
     * TODO: Write general description for this element
     */
    ENUM_40: 40,

    /**
     * TODO: Write general description for this element
     */
    ENUM_44: 44,

    /**
     * TODO: Write general description for this element
     */
    ENUM_48: 48,

    /**
     * TODO: Write general description for this element
     */
    ENUM_52: 52,

    /**
     * TODO: Write general description for this element
     */
    ENUM_56: 56,

    /**
     * TODO: Write general description for this element
     */
    ENUM_60: 60,

    /**
     * TODO: Write general description for this element
     */
    ENUM_64: 64,

    /**
     * TODO: Write general description for this element
     */
    ENUM_100: 100,

    /**
     * TODO: Write general description for this element
     */
    ENUM_104: 104,

    /**
     * TODO: Write general description for this element
     */
    ENUM_108: 108,

    /**
     * TODO: Write general description for this element
     */
    ENUM_112: 112,

    /**
     * TODO: Write general description for this element
     */
    ENUM_116: 116,

    /**
     * TODO: Write general description for this element
     */
    ENUM_120: 120,

    /**
     * TODO: Write general description for this element
     */
    ENUM_124: 124,

    /**
     * TODO: Write general description for this element
     */
    ENUM_128: 128,

    /**
     * TODO: Write general description for this element
     */
    ENUM_132: 132,

    /**
     * TODO: Write general description for this element
     */
    ENUM_136: 136,

    /**
     * TODO: Write general description for this element
     */
    ENUM_140: 140,

    /**
     * TODO: Write general description for this element
     */
    ENUM_144: 144,

    /**
     * TODO: Write general description for this element
     */
    ENUM_149: 149,

    /**
     * TODO: Write general description for this element
     */
    ENUM_153: 153,

    /**
     * TODO: Write general description for this element
     */
    ENUM_157: 157,

    /**
     * TODO: Write general description for this element
     */
    ENUM_161: 161,

    /**
     * TODO: Write general description for this element
     */
    ENUM_165: 165,

    /**
     * TODO: Write general description for this element
     */
    ENUM_169: 169,

    /**
     * TODO: Write general description for this element
     */
    ENUM_173: 173,

    /**
     * TODO: Write general description for this element
     */
    ENUM_177: 177,

};

module.exports = Channel1Enum;
