/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of ContentFiltering
 */
class ContentFiltering extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.allowedUrlPatterns = this.constructor.getValue(obj.allowedUrlPatterns);
        this.blockedUrlPatterns = this.constructor.getValue(obj.blockedUrlPatterns);
        this.blockedUrlCategories = this.constructor.getValue(obj.blockedUrlCategories);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            {
                name: 'allowedUrlPatterns',
                realName: 'allowedUrlPatterns',
                type: 'AllowedUrlPatterns',
            },
            {
                name: 'blockedUrlPatterns',
                realName: 'blockedUrlPatterns',
                type: 'BlockedUrlPatterns',
            },
            {
                name: 'blockedUrlCategories',
                realName: 'blockedUrlCategories',
                type: 'BlockedUrlCategories',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = ContentFiltering;
