/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ControllerDisconnectionBehaviorEnum = {

    /**
     * TODO: Write general description for this element
     */
    OPEN: 'open',

    /**
     * TODO: Write general description for this element
     */
    RESTRICTED: 'restricted',

    /**
     * TODO: Write general description for this element
     */
    MDEFAULT: 'default',

};

module.exports = ControllerDisconnectionBehaviorEnum;
