/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateNetworkApplianceTrafficShapingCustomPerformanceClass
 */
class CreateNetworkApplianceTrafficShapingCustomPerformanceClass extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.name = this.constructor.getValue(obj.name);
        this.maxLatency = this.constructor.getValue(obj.maxLatency);
        this.maxJitter = this.constructor.getValue(obj.maxJitter);
        this.maxLossPercentage = this.constructor.getValue(obj.maxLossPercentage);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'name', realName: 'name' },
            { name: 'maxLatency', realName: 'maxLatency' },
            { name: 'maxJitter', realName: 'maxJitter' },
            { name: 'maxLossPercentage', realName: 'maxLossPercentage' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateNetworkApplianceTrafficShapingCustomPerformanceClass;
