/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of CreateNetworkFirmwareUpgradesRollback
 */
class CreateNetworkFirmwareUpgradesRollback extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.product = this.constructor.getValue(obj.product);
        this.time = this.constructor.getValue(obj.time);
        this.reasons = this.constructor.getValue(obj.reasons);
        this.toVersion = this.constructor.getValue(obj.toVersion);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'product', realName: 'product' },
            { name: 'time', realName: 'time', isDateTime: true, dateTimeValue: 'rfc3339' },
            { name: 'reasons', realName: 'reasons', array: true, type: 'Reason' },
            { name: 'toVersion', realName: 'toVersion', type: 'ToVersion7' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = CreateNetworkFirmwareUpgradesRollback;
