/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const DayOfWeekEnum = {

    /**
     * TODO: Write general description for this element
     */
    SUN: 'sun',

    /**
     * TODO: Write general description for this element
     */
    MON: 'mon',

    /**
     * TODO: Write general description for this element
     */
    TUE: 'tue',

    /**
     * TODO: Write general description for this element
     */
    WED: 'wed',

    /**
     * TODO: Write general description for this element
     */
    THU: 'thu',

    /**
     * TODO: Write general description for this element
     */
    FRI: 'fri',

    /**
     * TODO: Write general description for this element
     */
    SAT: 'sat',

    /**
     * TODO: Write general description for this element
     */
    SUNDAY: 'sunday',

    /**
     * TODO: Write general description for this element
     */
    MONDAY: 'monday',

    /**
     * TODO: Write general description for this element
     */
    TUESDAY: 'tuesday',

    /**
     * TODO: Write general description for this element
     */
    WEDNESDAY: 'wednesday',

    /**
     * TODO: Write general description for this element
     */
    THURSDAY: 'thursday',

    /**
     * TODO: Write general description for this element
     */
    FRIDAY: 'friday',

    /**
     * TODO: Write general description for this element
     */
    SATURDAY: 'saturday',

};

module.exports = DayOfWeekEnum;
