/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const DefaultUplinkEnum = {

    /**
     * TODO: Write general description for this element
     */
    WAN_1: 'wan1',

    /**
     * TODO: Write general description for this element
     */
    WAN_2: 'wan2',

};

module.exports = DefaultUplinkEnum;
