/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const DeviceTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    COMBINED: 'combined',

    /**
     * TODO: Write general description for this element
     */
    WIRELESS: 'wireless',

    /**
     * TODO: Write general description for this element
     */
    SWITCH: 'switch',

    /**
     * TODO: Write general description for this element
     */
    APPLIANCE: 'appliance',

};

module.exports = DeviceTypeEnum;
