/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const DevicePolicy2Enum = {

    /**
     * TODO: Write general description for this element
     */
    ALLOWED: 'Allowed',

    /**
     * TODO: Write general description for this element
     */
    BLOCKED: 'Blocked',

    /**
     * TODO: Write general description for this element
     */
    NORMAL: 'Normal',

    /**
     * TODO: Write general description for this element
     */
    ENUM_GROUP_POLICY: 'Group policy',

};

module.exports = DevicePolicy2Enum;
