/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const DeviceType1Enum = {

    /**
     * TODO: Write general description for this element
     */
    ANDROID: 'Android',

    /**
     * TODO: Write general description for this element
     */
    BLACK_BERRY: 'BlackBerry',

    /**
     * TODO: Write general description for this element
     */
    ENUM_CHROME_OS: 'Chrome OS',

    /**
     * TODO: Write general description for this element
     */
    I_PAD: 'iPad',

    /**
     * TODO: Write general description for this element
     */
    I_PHONE: 'iPhone',

    /**
     * TODO: Write general description for this element
     */
    I_POD: 'iPod',

    /**
     * TODO: Write general description for this element
     */
    ENUM_MAC_OS_X: 'Mac OS X',

    /**
     * TODO: Write general description for this element
     */
    WINDOWS: 'Windows',

    /**
     * TODO: Write general description for this element
     */
    ENUM_WINDOWS_PHONE: 'Windows Phone',

    /**
     * TODO: Write general description for this element
     */
    ENUM_BN_NOOK: 'B&N Nook',

    /**
     * TODO: Write general description for this element
     */
    ENUM_OTHER_OS: 'Other OS',

};

module.exports = DeviceType1Enum;
