/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of DeviceTypePolicy
 */
class DeviceTypePolicy extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.deviceType = this.constructor.getValue(obj.deviceType);
        this.devicePolicy = this.constructor.getValue(obj.devicePolicy);
        this.groupPolicyId = this.constructor.getValue(obj.groupPolicyId);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'deviceType', realName: 'deviceType' },
            { name: 'devicePolicy', realName: 'devicePolicy' },
            { name: 'groupPolicyId', realName: 'groupPolicyId' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = DeviceTypePolicy;
