/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const DhcpModeEnum = {

    /**
     * TODO: Write general description for this element
     */
    DHCP_DISABLED: 'dhcpDisabled',

    /**
     * TODO: Write general description for this element
     */
    DHCP_RELAY: 'dhcpRelay',

    /**
     * TODO: Write general description for this element
     */
    DHCP_SERVER: 'dhcpServer',

};

module.exports = DhcpModeEnum;
