/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const DnsNameserversOptionEnum = {

    /**
     * TODO: Write general description for this element
     */
    GOOGLE_PUBLIC_DNS: 'googlePublicDns',

    /**
     * TODO: Write general description for this element
     */
    OPEN_DNS: 'openDns',

    /**
     * TODO: Write general description for this element
     */
    CUSTOM: 'custom',

};

module.exports = DnsNameserversOptionEnum;
