/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const FailOverCriterionEnum = {

    /**
     * TODO: Write general description for this element
     */
    POOR_PERFORMANCE: 'poorPerformance',

    /**
     * TODO: Write general description for this element
     */
    UPLINK_DOWN: 'uplinkDown',

};

module.exports = FailOverCriterionEnum;
