/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const HostModeEnum = {

    /**
     * TODO: Write general description for this element
     */
    SINGLE_HOST: 'Single-Host',

    /**
     * TODO: Write general description for this element
     */
    MULTI_DOMAIN: 'Multi-Domain',

    /**
     * TODO: Write general description for this element
     */
    MULTI_HOST: 'Multi-Host',

    /**
     * TODO: Write general description for this element
     */
    MULTI_AUTH: 'Multi-Auth',

};

module.exports = HostModeEnum;
