/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const HourOfDayEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_000: '0:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_100: '1:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_200: '2:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_300: '3:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_400: '4:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_500: '5:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_600: '6:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_700: '7:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_800: '8:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_900: '9:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1000: '10:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1100: '11:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1200: '12:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1300: '13:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1400: '14:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1500: '15:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1600: '16:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1700: '17:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1800: '18:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1900: '19:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_2000: '20:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_2100: '21:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_2200: '22:00',

    /**
     * TODO: Write general description for this element
     */
    ENUM_2300: '23:00',

};

module.exports = HourOfDayEnum;
