/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const IkePrfAlgoEnum = {

    /**
     * TODO: Write general description for this element
     */
    PRFSHA_256: 'prfsha256',

    /**
     * TODO: Write general description for this element
     */
    PRFSHA_1: 'prfsha1',

    /**
     * TODO: Write general description for this element
     */
    PRFMD_5: 'prfmd5',

    /**
     * TODO: Write general description for this element
     */
    MDEFAULT: 'default',

};

module.exports = IkePrfAlgoEnum;
