/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const IncludedSeverityEnum = {

    /**
     * TODO: Write general description for this element
     */
    GOOD: 'good',

    /**
     * TODO: Write general description for this element
     */
    INFO: 'info',

    /**
     * TODO: Write general description for this element
     */
    WARN: 'warn',

    /**
     * TODO: Write general description for this element
     */
    BAD: 'bad',

};

module.exports = IncludedSeverityEnum;
