/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Ldap
 */
class Ldap extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.servers = this.constructor.getValue(obj.servers);
        this.credentials = this.constructor.getValue(obj.credentials);
        this.baseDistinguishedName = this.constructor.getValue(obj.baseDistinguishedName);
        this.serverCaCertificate = this.constructor.getValue(obj.serverCaCertificate);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'servers', realName: 'servers', array: true, type: 'Server1' },
            { name: 'credentials', realName: 'credentials', type: 'Credentials' },
            { name: 'baseDistinguishedName', realName: 'baseDistinguishedName' },
            {
                name: 'serverCaCertificate',
                realName: 'serverCaCertificate',
                type: 'ServerCaCertificate',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Ldap;
