/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of LocalRadius
 */
class LocalRadius extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.cacheTimeout = this.constructor.getValue(obj.cacheTimeout);
        this.passwordAuthentication = this.constructor.getValue(obj.passwordAuthentication);
        this.certificateAuthentication = this.constructor.getValue(obj.certificateAuthentication);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'cacheTimeout', realName: 'cacheTimeout' },
            {
                name: 'passwordAuthentication',
                realName: 'passwordAuthentication',
                type: 'PasswordAuthentication',
            },
            {
                name: 'certificateAuthentication',
                realName: 'certificateAuthentication',
                type: 'CertificateAuthentication',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = LocalRadius;
