/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Mode1Enum = {

    /**
     * TODO: Write general description for this element
     */
    ENABLED: 'enabled',

    /**
     * TODO: Write general description for this element
     */
    DISABLED: 'disabled',

};

module.exports = Mode1Enum;
