/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const MotionDetectorVersionEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_1: 1,

    /**
     * TODO: Write general description for this element
     */
    ENUM_2: 2,

};

module.exports = MotionDetectorVersionEnum;
