/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const MulticastRouting1Enum = {

    /**
     * TODO: Write general description for this element
     */
    DISABLED: 'disabled',

    /**
     * TODO: Write general description for this element
     */
    ENABLED: 'enabled',

    /**
     * TODO: Write general description for this element
     */
    ENUM_IGMP_SNOOPING_QUERIER: 'IGMP snooping querier',

};

module.exports = MulticastRouting1Enum;
