/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const OrgAccess2Enum = {

    /**
     * TODO: Write general description for this element
     */
    NONE: 'none',

    /**
     * TODO: Write general description for this element
     */
    READONLY: 'read-only',

    /**
     * TODO: Write general description for this element
     */
    FULL: 'full',

};

module.exports = OrgAccess2Enum;
