/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Policy3Enum = {

    /**
     * TODO: Write general description for this element
     */
    DENY: 'deny',

};

module.exports = Policy3Enum;
