/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const PreferredUplink1Enum = {

    /**
     * TODO: Write general description for this element
     */
    WAN_1: 'wan1',

    /**
     * TODO: Write general description for this element
     */
    WAN_2: 'wan2',

    /**
     * TODO: Write general description for this element
     */
    BEST_FOR_VO_IP: 'bestForVoIP',

    /**
     * TODO: Write general description for this element
     */
    LOAD_BALANCING: 'loadBalancing',

    /**
     * TODO: Write general description for this element
     */
    DEFAULT_UPLINK: 'defaultUplink',

};

module.exports = PreferredUplink1Enum;
