/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ProductEnum = {

    /**
     * TODO: Write general description for this element
     */
    WIRELESS: 'wireless',

    /**
     * TODO: Write general description for this element
     */
    SWITCH: 'switch',

    /**
     * TODO: Write general description for this element
     */
    APPLIANCE: 'appliance',

    /**
     * TODO: Write general description for this element
     */
    CAMERA: 'camera',

    /**
     * TODO: Write general description for this element
     */
    VMX_HOST: 'vmxHost',

    /**
     * TODO: Write general description for this element
     */
    CELLULAR_GATEWAY: 'cellularGateway',

};

module.exports = ProductEnum;
