/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const ProductTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    WIRELESS: 'wireless',

    /**
     * TODO: Write general description for this element
     */
    APPLIANCE: 'appliance',

    /**
     * TODO: Write general description for this element
     */
    SWITCH: 'switch',

    /**
     * TODO: Write general description for this element
     */
    SYSTEMS_MANAGER: 'systemsManager',

    /**
     * TODO: Write general description for this element
     */
    CAMERA: 'camera',

    /**
     * TODO: Write general description for this element
     */
    CELLULAR_GATEWAY: 'cellularGateway',

    /**
     * TODO: Write general description for this element
     */
    ENVIRONMENTAL: 'environmental',

};

module.exports = ProductTypeEnum;
