/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Protocol9Enum = {

    /**
     * TODO: Write general description for this element
     */
    RADIUS: 'radius',

    /**
     * TODO: Write general description for this element
     */
    SNMP: 'snmp',

    /**
     * TODO: Write general description for this element
     */
    SYSLOG: 'syslog',

};

module.exports = Protocol9Enum;
