/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Protocol12Enum = {

    /**
     * TODO: Write general description for this element
     */
    RADIUS: 'radius',

    /**
     * TODO: Write general description for this element
     */
    SNMP: 'snmp',

    /**
     * TODO: Write general description for this element
     */
    SYSLOG: 'syslog',

    /**
     * TODO: Write general description for this element
     */
    LDAP: 'ldap',

};

module.exports = Protocol12Enum;
