/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Protocol3Enum = {

    /**
     * TODO: Write general description for this element
     */
    TCP: 'tcp',

    /**
     * TODO: Write general description for this element
     */
    UDP: 'udp',

};

module.exports = Protocol3Enum;
