/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Protocol11Enum = {

    /**
     * TODO: Write general description for this element
     */
    ANY: 'ANY',

    /**
     * TODO: Write general description for this element
     */
    TCP: 'TCP',

    /**
     * TODO: Write general description for this element
     */
    UDP: 'UDP',

};

module.exports = Protocol11Enum;
