/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const RadiusLoadBalancingPolicyEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_STRICT_PRIORITY_ORDER: 'Strict priority order',

    /**
     * TODO: Write general description for this element
     */
    ENUM_ROUND_ROBIN: 'Round robin',

};

module.exports = RadiusLoadBalancingPolicyEnum;
