/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const RadiusAttributeForGroupPoliciesEnum = {

    /**
     * TODO: Write general description for this element
     */
    FILTER_ID: 'Filter-Id',

    /**
     * TODO: Write general description for this element
     */
    REPLY_MESSAGE: 'Reply-Message',

    /**
     * TODO: Write general description for this element
     */
    AIRESPACE_ACL_NAME: 'Airespace-ACL-Name',

    /**
     * TODO: Write general description for this element
     */
    ARUBA_USER_ROLE: 'Aruba-User-Role',

};

module.exports = RadiusAttributeForGroupPoliciesEnum;
