/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const RadiusFailoverPolicyEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_DENY_ACCESS: 'Deny access',

    /**
     * TODO: Write general description for this element
     */
    ENUM_ALLOW_ACCESS: 'Allow access',

};

module.exports = RadiusFailoverPolicyEnum;
