/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const SortOrderEnum = {

    /**
     * TODO: Write general description for this element
     */
    ASCENDING: 'ascending',

    /**
     * TODO: Write general description for this element
     */
    DESCENDING: 'descending',

};

module.exports = SortOrderEnum;
