/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const StatusEnum = {

    /**
     * TODO: Write general description for this element
     */
    PENDING: 'pending',

    /**
     * TODO: Write general description for this element
     */
    COMPLETED: 'completed',

    /**
     * TODO: Write general description for this element
     */
    FAILED: 'failed',

};

module.exports = StatusEnum;
