/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const TagsFilterTypeEnum = {

    /**
     * TODO: Write general description for this element
     */
    WITH_ANY_TAGS: 'withAnyTags',

    /**
     * TODO: Write general description for this element
     */
    WITH_ALL_TAGS: 'withAllTags',

};

module.exports = TagsFilterTypeEnum;
