/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const TimeLimitEnum = {

    /**
     * TODO: Write general description for this element
     */
    ENUM_1_HOUR: '1 hour',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1_DAY: '1 day',

    /**
     * TODO: Write general description for this element
     */
    ENUM_1_WEEK: '1 week',

    /**
     * TODO: Write general description for this element
     */
    ENUM_30_DAYS: '30 days',

};

module.exports = TimeLimitEnum;
