/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Type4Enum = {

    /**
     * TODO: Write general description for this element
     */
    APPLICATION_CATEGORY: 'applicationCategory',

    /**
     * TODO: Write general description for this element
     */
    APPLICATION: 'application',

    /**
     * TODO: Write general description for this element
     */
    CUSTOM: 'custom',

};

module.exports = Type4Enum;
