/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Type14Enum = {

    /**
     * TODO: Write general description for this element
     */
    ASSOC: 'assoc',

    /**
     * TODO: Write general description for this element
     */
    DISASSOC: 'disassoc',

    /**
     * TODO: Write general description for this element
     */
    AUTH: 'auth',

    /**
     * TODO: Write general description for this element
     */
    DEAUTH: 'deauth',

    /**
     * TODO: Write general description for this element
     */
    DNS: 'dns',

    /**
     * TODO: Write general description for this element
     */
    DHCP: 'dhcp',

    /**
     * TODO: Write general description for this element
     */
    ROAM: 'roam',

    /**
     * TODO: Write general description for this element
     */
    CONNECTION: 'connection',

    /**
     * TODO: Write general description for this element
     */
    STICKY: 'sticky',

};

module.exports = Type14Enum;
