/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Type17Enum = {

    /**
     * TODO: Write general description for this element
     */
    TRUNK: 'trunk',

    /**
     * TODO: Write general description for this element
     */
    ACCESS: 'access',

};

module.exports = Type17Enum;
