/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Type1Enum = {

    /**
     * TODO: Write general description for this element
     */
    TEXT: 'text',

    /**
     * TODO: Write general description for this element
     */
    IP: 'ip',

    /**
     * TODO: Write general description for this element
     */
    INTEGER: 'integer',

    /**
     * TODO: Write general description for this element
     */
    HEX: 'hex',

};

module.exports = Type1Enum;
