/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Type5Enum = {

    /**
     * TODO: Write general description for this element
     */
    BUILTIN: 'builtin',

    /**
     * TODO: Write general description for this element
     */
    CUSTOM: 'custom',

};

module.exports = Type5Enum;
