/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of UpdateDeviceCameraSense
 */
class UpdateDeviceCameraSense extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.senseEnabled = this.constructor.getValue(obj.senseEnabled);
        this.mqttBrokerId = this.constructor.getValue(obj.mqttBrokerId);
        this.detectionModelId = this.constructor.getValue(obj.detectionModelId);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'senseEnabled', realName: 'senseEnabled' },
            { name: 'mqttBrokerId', realName: 'mqttBrokerId' },
            { name: 'detectionModelId', realName: 'detectionModelId' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = UpdateDeviceCameraSense;
