/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of UpdateNetworkApplianceTrafficShapingUplinkSelection
 */
class UpdateNetworkApplianceTrafficShapingUplinkSelection extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.activeActiveAutoVpnEnabled = this.constructor.getValue(obj.activeActiveAutoVpnEnabled);
        this.defaultUplink = this.constructor.getValue(obj.defaultUplink);
        this.loadBalancingEnabled = this.constructor.getValue(obj.loadBalancingEnabled);
        this.wanTrafficUplinkPreferences =
          this.constructor.getValue(obj.wanTrafficUplinkPreferences);
        this.vpnTrafficUplinkPreferences =
          this.constructor.getValue(obj.vpnTrafficUplinkPreferences);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'activeActiveAutoVpnEnabled', realName: 'activeActiveAutoVpnEnabled' },
            { name: 'defaultUplink', realName: 'defaultUplink' },
            { name: 'loadBalancingEnabled', realName: 'loadBalancingEnabled' },
            {
                name: 'wanTrafficUplinkPreferences',
                realName: 'wanTrafficUplinkPreferences',
                array: true,
                type: 'WanTrafficUplinkPreference',
            },
            {
                name: 'vpnTrafficUplinkPreferences',
                realName: 'vpnTrafficUplinkPreferences',
                array: true,
                type: 'VpnTrafficUplinkPreference',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = UpdateNetworkApplianceTrafficShapingUplinkSelection;
