/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of UpdateNetworkGroupPolicy
 */
class UpdateNetworkGroupPolicy extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.name = this.constructor.getValue(obj.name);
        this.scheduling = this.constructor.getValue(obj.scheduling);
        this.bandwidth = this.constructor.getValue(obj.bandwidth);
        this.firewallAndTrafficShaping = this.constructor.getValue(obj.firewallAndTrafficShaping);
        this.contentFiltering = this.constructor.getValue(obj.contentFiltering);
        this.splashAuthSettings = this.constructor.getValue(obj.splashAuthSettings);
        this.vlanTagging = this.constructor.getValue(obj.vlanTagging);
        this.bonjourForwarding = this.constructor.getValue(obj.bonjourForwarding);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'name', realName: 'name' },
            { name: 'scheduling', realName: 'scheduling', type: 'Scheduling' },
            { name: 'bandwidth', realName: 'bandwidth', type: 'Bandwidth' },
            {
                name: 'firewallAndTrafficShaping',
                realName: 'firewallAndTrafficShaping',
                type: 'FirewallAndTrafficShaping',
            },
            { name: 'contentFiltering', realName: 'contentFiltering', type: 'ContentFiltering' },
            { name: 'splashAuthSettings', realName: 'splashAuthSettings' },
            { name: 'vlanTagging', realName: 'vlanTagging', type: 'VlanTagging' },
            { name: 'bonjourForwarding', realName: 'bonjourForwarding', type: 'BonjourForwarding' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = UpdateNetworkGroupPolicy;
