/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of UpdateDeviceWirelessRadioSettings
 */
class UpdateDeviceWirelessRadioSettings extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.rfProfileId = this.constructor.getValue(obj.rfProfileId);
        this.twoFourGhzSettings = this.constructor.getValue(obj.twoFourGhzSettings);
        this.fiveGhzSettings = this.constructor.getValue(obj.fiveGhzSettings);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'rfProfileId', realName: 'rfProfileId' },
            {
                name: 'twoFourGhzSettings',
                realName: 'twoFourGhzSettings',
                type: 'TwoFourGhzSettings',
            },
            { name: 'fiveGhzSettings', realName: 'fiveGhzSettings', type: 'FiveGhzSettings' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = UpdateDeviceWirelessRadioSettings;
