/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of UpdateOrganizationSamlIdp
 */
class UpdateOrganizationSamlIdp extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.x509certSha1Fingerprint = this.constructor.getValue(obj.x509certSha1Fingerprint);
        this.sloLogoutUrl = this.constructor.getValue(obj.sloLogoutUrl);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'x509certSha1Fingerprint', realName: 'x509certSha1Fingerprint' },
            { name: 'sloLogoutUrl', realName: 'sloLogoutUrl' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = UpdateOrganizationSamlIdp;
