/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of UpdateNetworkMerakiAuthUser
 */
class UpdateNetworkMerakiAuthUser extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.name = this.constructor.getValue(obj.name);
        this.password = this.constructor.getValue(obj.password);
        this.emailPasswordToUser = this.constructor.getValue(obj.emailPasswordToUser);
        this.authorizations = this.constructor.getValue(obj.authorizations);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'name', realName: 'name' },
            { name: 'password', realName: 'password' },
            { name: 'emailPasswordToUser', realName: 'emailPasswordToUser' },
            {
                name: 'authorizations',
                realName: 'authorizations',
                array: true,
                type: 'Authorization1',
            },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = UpdateNetworkMerakiAuthUser;
