/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const UpgradeStrategyEnum = {

    /**
     * TODO: Write general description for this element
     */
    MINIMIZE_UPGRADE_TIME: 'minimizeUpgradeTime',

    /**
     * TODO: Write general description for this element
     */
    MINIMIZE_CLIENT_DOWNTIME: 'minimizeClientDowntime',

};

module.exports = UpgradeStrategyEnum;
