/**
 * MerakiDashboardAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const UsedStateEnum = {

    /**
     * TODO: Write general description for this element
     */
    USED: 'used',

    /**
     * TODO: Write general description for this element
     */
    UNUSED: 'unused',

};

module.exports = UsedStateEnum;
